apiVersion: v1
data:
  cacert: <YOUR_OPENSTACK_API_CERT_BASE64>
  clouds.yaml: <YOUR_OPENSTACK_CLOUDS_YAML_BASE64>
kind: Secret
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
  name: <CLUSTER_NAME>-cloud-config

---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: <CLUSTER_NAME>-md-0
spec:
  template:
    spec:
      # ntp:
      #   servers:
      #     - 212.132.97.26
      #   enabled: true
      files: 
      - path: /etc/chrony/chrony.conf
        owner: "root:root"
        permissions: "0640"
        content: |
          confdir /etc/chrony/conf.d
          pool 192.168.10.1 iburst
          sourcedir /run/chrony-dhcp
          sourcedir /etc/chrony/sources.d
          keyfile /etc/chrony/chrony.keys
          driftfile /var/lib/chrony/chrony.drift
          ntsdumpdir /var/lib/chrony
          logdir /var/log/chrony
          maxupdateskew 100.0
          rtcsync
          makestep 1 3
          leapsectz right/UTC
      - path: /etc/systemd/system/containerd.service.d/http-proxy.conf
        owner: "root:root"
        permissions: "0640"
        content: |
          [Service]
          Environment="HTTP_PROXY=http://192.168.10.79:8080" 
          Environment="HTTPS_PROXY=http://192.168.10.79:8080"
          Environment="NO_PROXY=192.168.0.0/16,172.16.0.0/12,10.0.0.0/8"
      postKubeadmCommands:
      - systemctl restart containerd
      - systemctl restart chrony

      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
            provider-id: openstack:///'{{ instance_id }}'
          name: '{{ local_hostname }}'

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: <CLUSTER_NAME>
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.244.0.0/16
    serviceDomain: cluster.local
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: <CLUSTER_NAME>-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: OpenStackCluster
    name: <CLUSTER_NAME>

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: <CLUSTER_NAME>-md-0
spec:
  clusterName: <CLUSTER_NAME>
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: <CLUSTER_NAME>-md-0
      clusterName: <CLUSTER_NAME>
      failureDomain: nova
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: OpenStackMachineTemplate
        name: <CLUSTER_NAME>-md-0
      version: <KUBERNETES_VERSION>

---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: <CLUSTER_NAME>-control-plane
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: external
      controllerManager:
        extraArgs:
          cloud-provider: external
    # ntp:
    #     servers:
    #       - 212.132.97.26
    #     enabled: true
    files: 
    - path: /etc/chrony/chrony.conf
      owner: "root:root"
      permissions: "0640"
      content: |
        confdir /etc/chrony/conf.d
        pool <YOUR_NTP_SERVER_ADDRESS> iburst
        sourcedir /run/chrony-dhcp
        sourcedir /etc/chrony/sources.d
        keyfile /etc/chrony/chrony.keys
        driftfile /var/lib/chrony/chrony.drift
        ntsdumpdir /var/lib/chrony
        logdir /var/log/chrony
        maxupdateskew 100.0
        rtcsync
        makestep 1 3
        leapsectz right/UTC
    - path: /etc/systemd/system/containerd.service.d/http-proxy.conf
      owner: "root:root"
      permissions: "0640"
      content: |
        [Service]
        Environment="HTTP_PROXY=http://<YOUR_PROXY_SERVER_ADDRESS>:8080" 
        Environment="HTTPS_PROXY=http://<YOUR_PROXY_SERVER_ADDRESS>:8080"
        Environment="NO_PROXY=192.168.0.0/16,172.16.0.0/12,10.0.0.0/8"
    postKubeadmCommands:
      - systemctl restart containerd
      - systemctl restart chrony

    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: openstack:///'{{ instance_id }}'
        name: '{{ local_hostname }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: openstack:///'{{ instance_id }}'
        name: '{{ local_hostname }}'
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: OpenStackMachineTemplate
      name: <CLUSTER_NAME>-control-plane
  replicas: 1
  version: <KUBERNETES_VERSION>

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackCluster
metadata:
  name: <CLUSTER_NAME>
spec:
  apiServerLoadBalancer:
    # enabled: true
    enabled: false
  externalNetwork:
    id: <YOUR_OPENSTACK_EXTERNAL_NET_ID>
  identityRef:
    cloudName: openstack
    name: <CLUSTER_NAME>-cloud-config
  managedSecurityGroups:
    allNodesSecurityGroupRules:
    - description: Created by cluster-api-provider-openstack - BGP (calico)
      direction: ingress
      etherType: IPv4
      name: BGP (Calico)
      portRangeMax: 179
      portRangeMin: 179
      protocol: tcp
      remoteManagedGroups:
      - controlplane
      - worker
    - description: Created by cluster-api-provider-openstack - IP-in-IP (calico)
      direction: ingress
      etherType: IPv4
      name: IP-in-IP (calico)
      protocol: "4"
      remoteManagedGroups:
      - controlplane
      - worker
  managedSubnets:
  - cidr: 10.10.1.0/24
    dnsNameservers:
    - 192.168.10.1

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: <CLUSTER_NAME>-control-plane
spec:
  template:
    spec:
      flavor: <DESIRED_FLAVOR>
      rootVolume:
        sizeGiB: 24
      image:
        filter:
          name: <YOUR_OPENSTACK_IMAGE_NAME>
      sshKeyName: <YOUR_OPENSTACK_SSH_KEYPAIR_NAME>

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: <CLUSTER_NAME>-md-0
spec:
  template:
    spec:
      flavor: <DESIRED_FLAVOR>
      rootVolume:
        sizeGiB: 24
      image:
        filter:
          name: <YOUR_OPENSTACK_IMAGE_NAME>
      sshKeyName: <YOUR_OPENSTACK_SSH_KEYPAIR_NAME>
